index:
  banner_img: https://cdn.pixabay.com/photo/2022/01/17/09/01/binary-6944162_960_720.jpg
  banner_img_height: 100
post:
  banner_img: https://cdn.pixabay.com/photo/2022/01/17/09/01/binary-6944162_960_720.jpg
  banner_img_height: 30
  default_index_img: https://cdn.pixabay.com/photo/2022/01/17/09/01/binary-6944162_960_720.jpg
archive:
  banner_img: https://cdn.pixabay.com/photo/2022/01/17/09/01/binary-6944162_960_720.jpg
  banner_img_height: 30
category:
  banner_img: https://cdn.pixabay.com/photo/2022/01/17/09/01/binary-6944162_960_720.jpg
  banner_img_height: 30
tag:
  banner_img: https://cdn.pixabay.com/photo/2022/01/17/09/01/binary-6944162_960_720.jpg
  banner_img_height: 30
about:
  banner_img: https://cdn.pixabay.com/photo/2022/01/17/09/01/binary-6944162_960_720.jpg
  banner_img_height: 30
links:
  banner_img: https://cdn.pixabay.com/photo/2022/01/17/09/01/binary-6944162_960_720.jpg
  banner_img_height: 30
  items:
    - title: 小丁的个人博客
      intro: 世间所有的相遇，都是久别重逢
      link: https://tding.top
      avatar: https://tding.top/images/avatar.webp
    - title: 米奇妙妙屋
      intro: 逐风揽月登九天 踏浪擒龙游四海
      link: https://ifibe.com/
      avatar: https://cdn.jsdelivr.net/gh/useblue/ucdn/imgs/avatar.webp
    - title: 荷戟独彷徨
      intro: 爱光学，爱生活，爱创造
      link: https://guanqr.com/
      avatar: https://cdn.jsdelivr.net/gh/guanqr/blog/static/icons/android-chrome-512x512.png
    - title: iMaeGoo’s Blog
      intro: 虹墨空间站
      link: https://www.imaegoo.com
      avatar: https://www.imaegoo.com/images/avatar.jpg
    - title: 琉仙の后花园
      intro: 一起来种花家呀
      link: https://blog.lx101.cn/
      avatar: https://z3.ax1x.com/2021/03/28/cS2LNV.jpg
    - title: LOGI
      intro: 会点代码的强迫症
      link: https://logi.im
      avatar: https://code.bdstatic.com/npm/logicdn@1.0.0/logi.im/usr/images/global/logo.webp